#!/bin/sh
/usr/bin/openocd \
	-f /usr/share/openocd/scripts/interface/stlink-v2.cfg \
	-f /usr/share/openocd/scripts/target/stm32f0x.cfg \
	-c init -c "reset halt" \
	-c "stm32f0x unlock 0" \
	-c "reset run" \
	-c shutdown
